plugins {
  id 'java'
  id 'io.gatling.gradle'
}

def generatedGatlingDir = project(':realword-openapi').layout.buildDirectory.dir('generated/java-gatling')

dependencies {
  gatlingCompileOnly 'org.projectlombok:lombok:1.18.46'
  gatlingAnnotationProcessor 'org.projectlombok:lombok:1.18.46'
  gatlingImplementation project(':gatling-core')
  gatlingImplementation project(':realword-openapi')
}

sourceSets {
  gatling {
    java.srcDir(generatedGatlingDir.map { it.dir('src/gatling/java') })
    resources.srcDir(generatedGatlingDir.map { it.dir('src/gatling/resources') })
  }
}

tasks.named('compileGatlingJava').configure {
  dependsOn ':realword-openapi:generateRealworldGatling'
}

tasks.named('processGatlingResources').configure {
  dependsOn ':realword-openapi:generateRealworldGatling'
}

tasks.named('build').configure {
  dependsOn tasks.named('compileGatlingJava')
}

gatling {
  enterprise {
    // Enterprise Cloud (https://cloud.gatling.io/) configuration reference: https://docs.gatling.io/reference/integrations/build-tools/gradle-plugin/
  }
}
